// Where the app points people when it sends them out of itself.
//
// The published site rather than a relative path: the guide is its own Astro
// build (`pnpm guide`, or `pnpm guide:dev` to work on it), so `./guide/` is a
// 404 under the app's `pnpm dev` — which is where these links get clicked while
// anyone is working on them.
const SITE = 'https://videoskillet.com/'

export const GUIDE_URL = `${SITE}guide/`
export const REPO_URL = 'https://github.com/cmdcolin/videoskillet'
// The query string written out: every param, and every control's key beside the
// name the panel gives it. Generated by scripts/docgen.mjs into public/, so it
// ships with the app rather than with the guide.
//
// Linked from the menu because nothing fetches a /llms.txt on its own. A model
// driving the app arrives in the page, finds 266 knobs it cannot aim a pointer
// at, and needs to be told — here — that there is an address-bar form of all of
// it. A person who wants to script the app needs the same page and has no other
// way to find it.
export const URL_API_URL = `${SITE}llms.txt`

export const openGuide = () => {
  window.open(GUIDE_URL, '_blank', 'noopener,noreferrer')
}

export const openUrlApi = () => {
  window.open(URL_API_URL, '_blank', 'noopener,noreferrer')
}
