// The doc content that comes out of the app's own tables.
//
// Two outputs. docs/EFFECTS.md is generated whole; docs/FEATURES.md is written
// by hand with one block filled in between markers, because part of its tour is
// prose the app already shows the reader, and re-saying it is how the two fall
// out of step.
//
// The page is an enumeration — every stage, every group, every control and the
// fault it models — and an enumeration written by hand drifts. It had: source B
// listed as taking a webcam it cannot take, and the user guide beside it had a
// morph ceiling two settings short and a stab length quoted at the default as
// though it were the range. None of those are wrong in the code, and nothing
// caught any of them.
//
// So nobody writes this file. `src/ui/controls.ts` is already the source of
// truth the panel renders from — a pure data module whose only two imports are
// `import type`, which is why node can load it here with no build step and no
// loader. Every `help` string is written to the rule the panel needs anyway
// (say what breaks in the hardware, not what the picture looks like), which is
// the same rule this page wants.
//
// The argued half of the old page — the tours, the reasons, the things with no
// control behind them — moved to docs/FEATURES.md and is still written by hand.
// Splitting them is what lets this half be generated at all: prose that makes a
// point cannot come out of a table, and a table should not be retyped as prose.
//
// Run: pnpm docgen, or `--check` to fail when a checked-in copy is stale.

// Loaded through vite rather than imported directly. `controls.ts` alone would
// import fine — its only two imports are `import type`, so node's type
// stripping handles it — but `modes.ts` imports `./clips` extensionless, the
// way every module in `src/` does, and that is vite's resolution rather than
// node's. Borrowing the app's own resolver is what keeps this script able to
// read any module in `src/`, instead of only the leaves that happen to have no
// value imports.
import { createServer } from 'vite'

import { execFileSync } from 'node:child_process'
import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

const vite = await createServer({
  server: { middlewareMode: true },
  appType: 'custom',
  logLevel: 'error',
})
const load = p => vite.ssrLoadModule(p)

// The shipped lists rather than the raw ones: the page describes what a reader
// can actually reach, and YouTube is backed by a dev-only bridge.
const { SHIPPED_B_MODES, SHIPPED_MODES, SOURCE_DESC } = await load(
  '/src/sources/modes.ts',
)
const {
  GROUPS,
  LOOP_STAGES,
  PHASE_ORDER,
  SOUND_BLURB,
  SOUND_JOIN,
  SOUND_STAGE,
  VIEW_JOIN,
  VIEW_STAGE,
} = await load('/src/ui/controls.ts')

const { DEFAULT_CONTROLS } = await load('/src/core/controls.ts')
const { PRESETS } = await load('/src/ui/presets.ts')
const { MOD_SOURCES, N_SLOTS, RATE_MAX, RATE_MIN } = await load(
  '/src/ui/modSlots.ts',
)

const EFFECTS = 'docs/EFFECTS.md'
const FEATURES = 'docs/FEATURES.md'
const LLMS = 'public/llms.txt'
const LLMS_FULL = 'public/llms-full.txt'

// Markdown table cells break on a raw pipe, and a few help strings carry one.
const cell = s => s.replaceAll('|', '\\|')

// A control's span, in the terms its own row shows. An enum has no span worth
// printing — its choices *are* the span — so it prints those instead.
const span = s => {
  if (s.choices !== undefined) {
    return s.choices.map(c => `\`${c}\``).join(' · ')
  }
  return `${s.min}–${s.max}${s.unit === '' ? '' : ` ${s.unit}`}`
}

const table = sliders =>
  [
    '| Control | Range | The fault it models |',
    '| --- | --- | --- |',
    ...sliders.map(
      s => `| **${cell(s.label)}** | ${cell(span(s))} | ${cell(s.help)} |`,
    ),
  ].join('\n')

const section = (heading, blurb, groups) =>
  groups.length === 0
    ? []
    : [
        `## ${heading}`,
        '',
        ...(blurb === undefined ? [] : [blurb, '']),
        ...groups.flatMap(g => [`### ${g.name}`, '', table(g.sliders), '']),
      ]

const at = place => GROUPS.filter(g => g.place === place)

// Each deck's own picker list, as the picker's own descriptions. The difference
// between the two lists is the fact the hand-written page got wrong, so it is
// stated here rather than left for a reader to diff.
const modeList = modes =>
  modes
    .filter(m => m !== 'none' && SOURCE_DESC[m] !== undefined)
    .map(m => `- ${SOURCE_DESC[m]}`)
    .join('\n')

const onlyA = SHIPPED_MODES.filter(m => !SHIPPED_B_MODES.includes(m))

const lines = [
  '<!-- Generated by scripts/docgen.mjs — do not edit; run `pnpm docgen`.',
  '     The hand-written half of this page is docs/FEATURES.md. -->',
  '',
  '# Effects',
  '',
  'Every control in the app, by where it sits on the signal path, with the fault',
  'each one models. Generated from the same control table the panel renders, so',
  'it cannot fall behind the app.',
  '',
  '[Features](FEATURES.md) is the other half — what the app *is*, argued rather',
  'than enumerated. Start there for the tour.',
  '',
  'Every control carries its text below on its own **?**, and both the filter box',
  'and `ctrl+k` search it, so a fault is findable here or in the app.',
  '',
  '## Sources',
  '',
  'What either deck can be fed:',
  '',
  modeList(SHIPPED_B_MODES),
  '',
  onlyA.length === 0
    ? ''
    : `Source A additionally takes ${onlyA.map(m => SOURCE_DESC[m].split(' — ')[0]).join(', ')}; source B does not.`,
  '',
  ...PHASE_ORDER.flatMap(p => section(p, undefined, at(p))),
  ...section(
    'Source B',
    'The second deck, with its own cable ahead of the mixer, so a fault can hit one source alone.',
    at('b'),
  ),
  ...LOOP_STAGES.flatMap(l =>
    section(`${l.name} — feedback loop`, `${l.what}.`, at(l.loop)),
  ),
  ...section(
    SOUND_STAGE,
    `Hangs off ${SOUND_JOIN} — ${SOUND_BLURB}.`,
    at('audio'),
  ),
  ...section(
    VIEW_STAGE,
    `Hangs off ${VIEW_JOIN}. Viewing conditions rather than faults: nothing here is in the signal path.`,
    at('view'),
  ),
  '',
  '---',
  '',
  '[Features](FEATURES.md) — the tour · [User guide](USER-GUIDE.md) — driving it ·',
  '[How it works](FAQ.md#how-does-it-actually-work) — the code',
  '',
]

const effects = lines.join('\n').replaceAll(/\n{3,}/g, '\n\n')

// The one block of FEATURES.md that is not written by hand. Each loop's `what`
// is the description the app itself gives that loop — the chain map opens it,
// and docs/EFFECTS.md heads the loop's section with it — so a tour that
// introduced the same three machines was restating text that already existed.
// It had already drifted into a paraphrase for the mixer and a verbatim copy
// for the camera, which is both failure modes at once.
//
// Only this block. The argument around it — that there are three, that the tape
// loop is not the Tape stage, what that means for how repeats decay — belongs
// to no single module and stays hand-written.
const LOOPS_OPEN =
  '<!-- generated:loops — from LOOP_STAGES in src/ui/controls.ts, via scripts/docgen.mjs -->'
const LOOPS_CLOSE = '<!-- /generated:loops -->'

const loopsBlock = LOOP_STAGES.map(l => `**${l.name}**: ${l.what}.`).join(
  '\n\n',
)

// The two pages written for something reading rather than looking.
//
// What they carry that no other page does is the *keys*. The query string takes
// `noiseIre`; every page in docs/ names that control "noise", because that is
// what the panel calls it — so a reader with the whole guide in front of it
// still cannot write a link. One line per control, key first, is the missing
// half, and it comes out of the same table the panel renders from.
//
// Why publish it at all, when nothing fetches /llms.txt on its own: because the
// query string is a complete remote control that the app never mentions, and
// the ways this file gets read — a coding agent grepping the repo, a person
// pasting the URL, the menu row that links to it — all need it to exist first.
//
// Kept out of the oxfmt pass below: it reflows markdown, and these are wrapped
// where their content wants it.
const llmsControl = s => {
  const range =
    s.choices === undefined
      ? `${s.min}..${s.max} step ${s.step}${s.unit === '' ? '' : ` ${s.unit}`}`
      : s.choices.map((c, i) => `${i}=${c}`).join(' ')
  return [
    `${s.key}  (${s.label})`,
    `  ${range}  default ${DEFAULT_CONTROLS[s.key]}`,
    `  ${s.help}`,
  ].join('\n')
}

const llmsFull = [
  '# videoskillet.js — every control',
  '',
  'Generated by scripts/docgen.mjs from the app’s own control table. The name in',
  'brackets is what the panel and the rest of the docs call the control; the key',
  'in front of it is what #set= and #mod= take. A value outside the range is',
  'clamped, not refused.',
  '',
  `Modulation sources for #mod=: ${MOD_SOURCES.map(s => s.value).join(', ')}.`,
  `Up to ${N_SLOTS} routings, rate ${RATE_MIN}..${RATE_MAX} Hz, depth 0..1.`,
  '',
  `Presets for #preset=: ${PRESETS.map(p => p.name).join(', ')}.`,
  '',
  ...GROUPS.flatMap(g => [
    `## ${g.name}`,
    '',
    ...g.sliders.map(s => `${llmsControl(s)}\n`),
  ]),
].join('\n')

// Checked against the live tables as it is assembled, because a worked example
// is the part a reader copies first and the only part of this page that can be
// wrong in a way nothing else notices — a control renamed under it leaves a link
// that quietly does nothing.
const example = (() => {
  const keys = ['headSwitchShiftUs', 'tintDeg']
  const preset = 'vhs'
  const known = new Set(GROUPS.flatMap(g => g.sliders.map(s => s.key)))
  for (const key of keys) {
    if (!known.has(key)) throw new Error(`${LLMS}: no control ${key}`)
  }
  if (!PRESETS.some(p => p.name === preset)) {
    throw new Error(`${LLMS}: no preset ${preset}`)
  }
  return `https://videoskillet.com/app/#preset=${preset}&set=${keys[0]}:9&mod=${keys[1]}:sine:0.2:0.4`
})()

const llms = [
  '# videoskillet.js',
  '',
  '> Real-time NTSC / VHS / composite-video simulation in WebGPU compute shaders.',
  '> Dot crawl, dropouts, head-switch wobble and video feedback are consequences of',
  '> a simulated analog signal path rather than filters drawn over the picture, so',
  '> the faults interact the way the hardware’s do.',
  '',
  'The app is at https://videoskillet.com/app/ — the root page is a landing page',
  'with an "Open the app" link. It needs WebGPU; on Linux that means Firefox',
  'Nightly or Chrome with WebGPU enabled.',
  '',
  '## The address bar is the remote control',
  '',
  'Every control, source and routing is reachable from the address bar, and the',
  'app mirrors the live board back into it. So the URL says what is on screen,',
  'and navigating to one puts it there — which is faster and steadier than',
  'operating 266 knobs by hand, whether the hand is a person’s or an agent’s.',
  '',
  'The parameters live after the `#`. Two shapes of link exist and both open the',
  'same board: the readable one the bar carries, and the packed `#p=…` the share',
  'button writes, which is that look in a couple of hundred characters and opaque',
  'to everything but the app. The readable one is both what to read and what to',
  'write; the packed one is for sending. Every link published before this carries',
  'its parameters on the `?` query instead and still opens.',
  '',
  '- `#preset=NAME` — a whole look. It resets what it does not name.',
  '- `#set=key:value,key:value` — controls by key, layered on top of any preset.',
  '  Out-of-range values clamp. This is the form to write, and the form the bar',
  '  shows: reading it back is how to check what a change actually did.',
  '- `#p=…` — the packed form the share button writes. Opaque; use `#set=`.',
  '- `#mod=target:source:rateHz:depth[:division]` — what is moving, comma-',
  '  separated. `target` is a control key, `source` one of the modulation',
  `  sources, up to ${N_SLOTS} of them.`,
  `- \`#src=\` / \`#srcb=\` — what each deck is fed: ${SHIPPED_B_MODES.filter(m => m !== 'none').join(', ')}.`,
  '- `#vurl=` / `#iurl=` / `#yt=` (and `#vurlb=`, `#iurlb=`, `#ytb=`) — a video,',
  '  image or YouTube clip on each deck.',
  '- `#text=` with `#crawl`, `#boil`, `#garble` — the teletype card; `#caption=`',
  '  puts a line on the line-21 caption track.',
  '- `#speeda=` / `#speedb=` / `#reverb=` / `#dry=` — playback and the audio send.',
  '- `#cuea=in,out` / `#cueb=in,out` — a loop over one deck, in seconds.',
  '- `#surprise` — a random look. `#debug` — the frame and timing readouts.',
  '- `#snow` — open on a burst of snow, `#snow=3` for three seconds of it. A',
  "  feedback look needs something to amplify and the reader's frame store",
  '  starts empty, so a board built on the loops opens black without it. The',
  '  burst heals off completely: the look is what the rest of the link says.',
  '',
  'Example — VHS with the head-switch tear pulled wide and the tint drifting:',
  '',
  `  ${example}`,
  '',
  'Changing only the fragment of a page that is already open does not reload it,',
  'so the app watches for that and reloads itself: a link opened in a tab already',
  'showing the app lands on the board it names, the same as a fresh one. Give it',
  'a moment to come back up before reading the result.',
  '',
  '## In the page',
  '',
  '`ctrl+k` (`⌘k`) opens a command palette that indexes every preset, control and',
  'verb by name and by the prose describing it. Typing a value after a name sets',
  'that control outright — "head switch 9", or "combiner ring" on a mode switch —',
  'and each row shows the control’s current reading, so the palette is also the',
  'quickest way to read the board back. Every slider is a native range input with',
  'a label; the drag surfaces (the framing boxes, the A/B lever) take arrow keys.',
  '',
  '## The rest',
  '',
  '- [Every control, with its key](https://videoskillet.com/llms-full.txt)',
  '- [Effects](https://videoskillet.com/guide/effects.html) — the fault each',
  '  control models',
  '- [User guide](https://videoskillet.com/guide/guide.html) — driving it',
  '- [How it works](https://videoskillet.com/guide/how-it-works.html) — the',
  '  signal path and the code',
  '- [Architecture](https://videoskillet.com/guide/architecture.html) — the pass',
  '  graph, for changing it',
  '- [AI usage](https://videoskillet.com/guide/ai.html) — working on this',
  '  codebase with an agent',
  '',
].join('\n')

const fillBlock = (text, open, close, body) => {
  const from = text.indexOf(open)
  const to = text.indexOf(close)
  if (from === -1 || to === -1) {
    throw new Error(`no generated block in ${FEATURES}`)
  }
  return `${text.slice(0, from + open.length)}\n\n${body}\n\n${text.slice(to)}`
}

await vite.close()

// Formatted here rather than left to `pnpm format`, and that is the difference
// between a check that holds and one that cries wolf: oxfmt reflows markdown,
// so a file this script emitted and a file oxfmt has since touched are not the
// same bytes, and --check would report every clean tree as stale. Generating
// what the formatter would have produced anyway settles it in one place.
//
// Resolved through node rather than spelled as `node_modules/.bin/oxfmt`, which
// is only there in a full checkout: a `git worktree` copy has no node_modules of
// its own, and node's own lookup walks up into the one it shares.
const require = createRequire(import.meta.url)
const oxfmtPkg = require.resolve('oxfmt/package.json')
const OXFMT = join(dirname(oxfmtPkg), require(oxfmtPkg).bin.oxfmt)
const SCRATCH = 'docs/.docgen-scratch.md'
const format = text => {
  writeFileSync(SCRATCH, text)
  try {
    execFileSync(OXFMT, [SCRATCH], { stdio: 'ignore' })
    return readFileSync(SCRATCH, 'utf8')
  } finally {
    rmSync(SCRATCH, { force: true })
  }
}

const pages = [
  { path: LLMS, text: llms },
  { path: LLMS_FULL, text: llmsFull },
  { path: EFFECTS, text: format(effects) },
  {
    path: FEATURES,
    text: format(
      fillBlock(
        readFileSync(FEATURES, 'utf8'),
        LOOPS_OPEN,
        LOOPS_CLOSE,
        loopsBlock,
      ),
    ),
  },
]

if (process.argv.includes('--check')) {
  const stale = pages.filter(p => readFileSync(p.path, 'utf8') !== p.text)
  if (stale.length > 0) {
    console.error(
      `stale — run \`pnpm docgen\`: ${stale.map(p => p.path).join(', ')}`,
    )
    process.exit(1)
  }
  console.log(`current: ${pages.map(p => p.path).join(', ')}`)
} else {
  for (const page of pages) {
    writeFileSync(page.path, page.text)
  }
  const n = GROUPS.reduce((a, g) => a + g.sliders.length, 0)
  console.log(
    `${EFFECTS}: ${GROUPS.length} groups, ${n} controls · ${FEATURES}: ${LOOP_STAGES.length} loops`,
  )
}
