// Stages src/core as a standalone JSR package under jsr/.
//
// Two things in the source resolve only under Vite: shaders arrive through
// `./shaders/x.wgsl?raw` and the buzz worklet through `?url`. The staged copy
// carries each shader as a generated `.wgsl.ts` module and the worklet as a
// `new URL(..., import.meta.url)` reference, so the package resolves under
// plain ESM. Nothing here is checked in — jsr/ is a build output.

import {
  cpSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'src/core')
const OUT = join(ROOT, 'jsr')
const CORE = join(OUT, 'core')

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))

const isTest = f => /\.(test|spec)\.ts$/.test(f)

rmSync(OUT, { recursive: true, force: true })
mkdirSync(CORE, { recursive: true })
cpSync(SRC, CORE, { recursive: true, filter: src => !isTest(src) })

// Each shader becomes a module exporting its source. The text is the file
// verbatim: the comment stripping in vite-plugin-wgsl is a bundle-size measure
// for the app, and a consumer compiling these wants the line numbers the
// errors name.
const shaderDir = join(CORE, 'gpu/shaders')
const shaders = readdirSync(shaderDir).filter(f => f.endsWith('.wgsl'))
for (const f of shaders) {
  const text = readFileSync(join(shaderDir, f), 'utf8')
  writeFileSync(
    join(shaderDir, `${f}.ts`),
    `// Generated by scripts/jsrpack.mjs from ${f}. Do not edit.\nconst src: string = ${JSON.stringify(text)}\nexport default src\n`,
  )
  rmSync(join(shaderDir, f))
}

const walk = dir =>
  readdirSync(dir, { withFileTypes: true }).flatMap(e =>
    e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)],
  )

let rewrote = 0
for (const file of walk(CORE).filter(f => f.endsWith('.ts'))) {
  const before = readFileSync(file, 'utf8')
  // JSR resolves module specifiers the way the browser does, so every
  // relative import needs its extension spelled out. The two Vite queries go
  // first, so the extension pass sees specifiers it can judge.
  const after = before
    .replace(/(\.wgsl)\?raw'/g, "$1.ts'")
    .replace(
      /^import workletUrl from '\.\/buzz\.worklet\.js\?url'$/m,
      "const workletUrl = new URL('./buzz.worklet.js', import.meta.url).href",
    )
    .replace(/(\bfrom '\.\.?\/[^']*?)'/g, (m, spec) =>
      /\.(ts|js|json)$/.test(spec) ? m : `${spec}.ts'`,
    )
  if (after !== before) {
    writeFileSync(file, after)
    rewrote++
  }
}

const leftover = walk(CORE).filter(f =>
  /\?(raw|url)'/.test(readFileSync(f, 'utf8')),
)
if (leftover.length > 0) {
  console.error(
    `unresolved Vite query imports in:\n${leftover
      .map(f => `  ${relative(ROOT, f)}`)
      .join('\n')}`,
  )
  process.exit(1)
}

writeFileSync(
  join(OUT, 'deno.json'),
  `${JSON.stringify(
    {
      name: '@videoskillet/videoskillet',
      version: pkg.version,
      license: pkg.license,
      exports: './mod.ts',
      // Deno's own libs carry the WebGPU interfaces but not the ambient
      // enum objects (`GPUBufferUsage`, `GPUTextureUsage`, `GPUMapMode`), so
      // the package types against the same @webgpu/types the app does.
      compilerOptions: {
        lib: ['esnext', 'dom', 'dom.iterable'],
        types: [`npm:@webgpu/types@${pkg.devDependencies['@webgpu/types']}`],
      },
      publish: { include: ['mod.ts', 'core/**', 'README.md', 'LICENSE'] },
    },
    null,
    2,
  )}\n`,
)

cpSync(join(ROOT, 'LICENSE'), join(OUT, 'LICENSE'))
cpSync(join(ROOT, 'scripts/jsr/mod.ts.tmpl'), join(OUT, 'mod.ts'))
cpSync(join(ROOT, 'scripts/jsr/README.md.tmpl'), join(OUT, 'README.md'))

console.log(
  `staged ${walk(CORE).length} files, ${shaders.length} shaders, ${rewrote} imports rewritten`,
)
